[[main]]
none = "none"

[[main]]
name = "About"
pageRef = "about"
identifier = "oXIjbK0uzT"
weight = 9_999

[[main]]
name = "Projects"
pageRef = "projects"
identifier = "zEokRkTeZj"
weight = 9_999

[[main]]
name = "Writing"
pageRef = "writing"
identifier = "VkWGeNX9GD"
weight = 9_999

[[footer]]
none = "none"
